name: op_trader
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pandas>=1.5.0
  - numpy>=1.24.0
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm>=4.64.0
  - colorlog>=6.7.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - flake8>=6.0.0
  - isort
  - black
  - mypy
  - yapf
  - psutil
  - requests
  - python-dotenv
  - pre-commit
  - gymnasium<0.29
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cudatoolkit=11.7
  - pip
  - pip:
      - MetaTrader5
      - optuna
      - openai
      - PyGithub
      - pydantic
